/*
 * Copyright (c) 2014, Bruce Schubert <bruce@emxsys.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     - Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *     - Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 *     - Neither the name of Bruce Schubert, Emxsys nor the names of its 
 *       contributors may be used to endorse or promote products derived
 *       from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.emxsys.wmt.cps.ui;

import com.terramenta.ribbon.RibbonActionReference;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.emxsys.wmt.cps.ui//Fuel//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = FuelTopComponent.PREFERRED_ID,
        iconBase = "com/emxsys/wmt/cps/images/flame-16x16.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_FuelAction",
        preferredID = FuelTopComponent.PREFERRED_ID
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "com.emxsys.wmt.cps.ui.FuelTopComponent")
@RibbonActionReference(path = "Menu/Window/Show",
        position = 210,
        priority = "top",
        description = "#CTL_FuelAction_Hint",
        tooltipTitle = "#CTL_FuelAction_TooltipTitle",
        tooltipBody = "#CTL_FuelAction_TooltipBody",
        tooltipIcon = "com/emxsys/wmt/cps/images/flame-16x16.png")
//        tooltipFooter = "#CTL_FuelAction_TooltipFooter",
//        tooltipFooterIcon = "com/terramenta/images/help.png")
@Messages({
    "CTL_FuelTopComponent=Fuel",
    "CTL_FuelTopComponent_Hint=The Fuel Model window.",
    "CTL_FuelAction=Fuel Model",
    "CTL_FuelAction_Hint=Show the Fuel Model.",
    "CTL_FuelAction_TooltipTitle=Show the Fuel Model",
    "CTL_FuelAction_TooltipBody=Activates the Fuel Model window used for visualizing "
    + "the fuel conditions influencing fire behavior.",
    "CTL_FuelAction_TooltipFooter=Press F1 for more help."
})
public final class FuelTopComponent extends TopComponent {

    public static final String PREFERRED_ID = "FuelTopComponent";
    private FuelModelPanel fuelModelPanel;
    private FuelMoisturePanel fuelMoisturePanel;
    private FuelMoistureScenarioPanel fuelMoistureScenarioPanel;

    public FuelTopComponent() {
        initComponents();
        createPanels();
        setName(Bundle.CTL_FuelTopComponent());
        setToolTipText(Bundle.CTL_FuelTopComponent_Hint());
        putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);

    }

    private void createPanels() {
        fuelModelPanel = new FuelModelPanel();
        fuelMoisturePanel = new FuelMoisturePanel();
        fuelMoistureScenarioPanel = new FuelMoistureScenarioPanel();

        // Assign panels to the Grid Layout
        add(fuelModelPanel);
        add(fuelMoisturePanel);
        add(fuelMoistureScenarioPanel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(3, 1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
